// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // CLI(db push/migrate)는 DIRECT_URL(5432 session). pgbouncer 트랜잭션 풀러(6543)는 DDL에 부적합.
    url: process.env["DIRECT_URL"],
  },
});
